#!/bin/bash
":"; exec emacs --script "$0" -f main -- "$@" # -*-emacs-lisp-*-

(defun main ()
  (require 'package)
  (add-to-list 'package-archives
               '("melpa" . "http://melpa.org/packages/"))

  ;; find package information from following archives
  ;; (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
  ;;                          ("marmalade" . "http://marmalade-repo.org/packages/")
  ;;                          ("melpa" . "http://melpa.milkbox.net/packages/")))

  (package-initialize)

  (setq packages-to-install '(auto-complete google-this))
  (mapcar (lambda (package)
            ;; install package if not already installed
            (unless (package-installed-p package)
              (package-install package)))
        packages-to-install)

  (kill-emacs))
